# Generated by Django 4.1.2 on 2022-10-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fecha_de_creacion',
            field=models.DateField(null=True),
        ),
    ]
