# Generated by Django 4.1.2 on 2022-10-05 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_persona_fecha_de_creacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona',
            new_name='Familiar',
        ),
        migrations.RenameField(
            model_name='familiar',
            old_name='Apellido',
            new_name='apellido',
        ),
    ]
